# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: PlayerCSStats.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='PlayerCSStats.proto',
  package='PlayerCSStats',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x13PlayerCSStats.proto\x12\rPlayerCSStats\"S\n\x07request\x12\x11\n\taccountid\x18\x01 \x01(\x04\x12\x10\n\x08seasonid\x18\x02 \x01(\r\x12\x10\n\x08gamemode\x18\x03 \x01(\r\x12\x11\n\tmatchmode\x18\x04 \x01(\r\"B\n\x08response\x12\x36\n\x07\x63sstats\x18\x01 \x01(\x0b\x32%.PlayerCSStats.AccountInfoWithTCStats\"\x94\x01\n\x16\x41\x63\x63ountInfoWithTCStats\x12\x11\n\taccountid\x18\x01 \x01(\x04\x12\x13\n\x0bgamesplayed\x18\x02 \x01(\r\x12\x0c\n\x04wins\x18\x03 \x01(\r\x12\r\n\x05kills\x18\x04 \x01(\r\x12\x35\n\rdetailedstats\x18\x05 \x01(\x0b\x32\x1e.PlayerCSStats.DetailedTCStats\"\x89\x03\n\x0f\x44\x65tailedTCStats\x12\x10\n\x08mvpcount\x18\x01 \x01(\r\x12\x13\n\x0b\x64oublekills\x18\x02 \x01(\r\x12\x13\n\x0btriplekills\x18\x03 \x01(\r\x12\x11\n\tfourkills\x18\x04 \x01(\r\x12\x0e\n\x06\x64\x61mage\x18\x05 \x01(\r\x12\x15\n\rheadshotkills\x18\x06 \x01(\r\x12\x12\n\nknockdowns\x18\x07 \x01(\r\x12\x10\n\x08revivals\x18\x08 \x01(\r\x12\x0f\n\x07\x61ssists\x18\t \x01(\r\x12\x0e\n\x06\x64\x65\x61ths\x18\n \x01(\r\x12\x12\n\nstreakwins\x18\x0b \x01(\r\x12\x15\n\rthrowingkills\x18\x0c \x01(\r\x12\x19\n\x11onegamemostdamage\x18\r \x01(\r\x12\x18\n\x10onegamemostkills\x18\x0e \x01(\r\x12\x14\n\x0cratingpoints\x18\x0f \x01(\x01\x12\x1a\n\x12ratingenabledgames\x18\x10 \x01(\r\x12\x15\n\rheadshotcount\x18\x11 \x01(\r\x12\x10\n\x08hitcount\x18\x12 \x01(\rb\x06proto3'
)




_REQUEST = _descriptor.Descriptor(
  name='request',
  full_name='PlayerCSStats.request',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='accountid', full_name='PlayerCSStats.request.accountid', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='seasonid', full_name='PlayerCSStats.request.seasonid', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='gamemode', full_name='PlayerCSStats.request.gamemode', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='matchmode', full_name='PlayerCSStats.request.matchmode', index=3,
      number=4, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=38,
  serialized_end=121,
)


_RESPONSE = _descriptor.Descriptor(
  name='response',
  full_name='PlayerCSStats.response',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='csstats', full_name='PlayerCSStats.response.csstats', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=123,
  serialized_end=189,
)


_ACCOUNTINFOWITHTCSTATS = _descriptor.Descriptor(
  name='AccountInfoWithTCStats',
  full_name='PlayerCSStats.AccountInfoWithTCStats',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='accountid', full_name='PlayerCSStats.AccountInfoWithTCStats.accountid', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='gamesplayed', full_name='PlayerCSStats.AccountInfoWithTCStats.gamesplayed', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='wins', full_name='PlayerCSStats.AccountInfoWithTCStats.wins', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='kills', full_name='PlayerCSStats.AccountInfoWithTCStats.kills', index=3,
      number=4, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='detailedstats', full_name='PlayerCSStats.AccountInfoWithTCStats.detailedstats', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=192,
  serialized_end=340,
)


_DETAILEDTCSTATS = _descriptor.Descriptor(
  name='DetailedTCStats',
  full_name='PlayerCSStats.DetailedTCStats',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='mvpcount', full_name='PlayerCSStats.DetailedTCStats.mvpcount', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='doublekills', full_name='PlayerCSStats.DetailedTCStats.doublekills', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='triplekills', full_name='PlayerCSStats.DetailedTCStats.triplekills', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='fourkills', full_name='PlayerCSStats.DetailedTCStats.fourkills', index=3,
      number=4, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='damage', full_name='PlayerCSStats.DetailedTCStats.damage', index=4,
      number=5, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='headshotkills', full_name='PlayerCSStats.DetailedTCStats.headshotkills', index=5,
      number=6, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='knockdowns', full_name='PlayerCSStats.DetailedTCStats.knockdowns', index=6,
      number=7, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='revivals', full_name='PlayerCSStats.DetailedTCStats.revivals', index=7,
      number=8, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='assists', full_name='PlayerCSStats.DetailedTCStats.assists', index=8,
      number=9, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='deaths', full_name='PlayerCSStats.DetailedTCStats.deaths', index=9,
      number=10, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='streakwins', full_name='PlayerCSStats.DetailedTCStats.streakwins', index=10,
      number=11, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='throwingkills', full_name='PlayerCSStats.DetailedTCStats.throwingkills', index=11,
      number=12, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='onegamemostdamage', full_name='PlayerCSStats.DetailedTCStats.onegamemostdamage', index=12,
      number=13, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='onegamemostkills', full_name='PlayerCSStats.DetailedTCStats.onegamemostkills', index=13,
      number=14, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='ratingpoints', full_name='PlayerCSStats.DetailedTCStats.ratingpoints', index=14,
      number=15, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='ratingenabledgames', full_name='PlayerCSStats.DetailedTCStats.ratingenabledgames', index=15,
      number=16, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='headshotcount', full_name='PlayerCSStats.DetailedTCStats.headshotcount', index=16,
      number=17, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='hitcount', full_name='PlayerCSStats.DetailedTCStats.hitcount', index=17,
      number=18, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=343,
  serialized_end=736,
)

_RESPONSE.fields_by_name['csstats'].message_type = _ACCOUNTINFOWITHTCSTATS
_ACCOUNTINFOWITHTCSTATS.fields_by_name['detailedstats'].message_type = _DETAILEDTCSTATS
DESCRIPTOR.message_types_by_name['request'] = _REQUEST
DESCRIPTOR.message_types_by_name['response'] = _RESPONSE
DESCRIPTOR.message_types_by_name['AccountInfoWithTCStats'] = _ACCOUNTINFOWITHTCSTATS
DESCRIPTOR.message_types_by_name['DetailedTCStats'] = _DETAILEDTCSTATS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

request = _reflection.GeneratedProtocolMessageType('request', (_message.Message,), {
  'DESCRIPTOR' : _REQUEST,
  '__module__' : 'PlayerCSStats_pb2'
  # @@protoc_insertion_point(class_scope:PlayerCSStats.request)
  })
_sym_db.RegisterMessage(request)

response = _reflection.GeneratedProtocolMessageType('response', (_message.Message,), {
  'DESCRIPTOR' : _RESPONSE,
  '__module__' : 'PlayerCSStats_pb2'
  # @@protoc_insertion_point(class_scope:PlayerCSStats.response)
  })
_sym_db.RegisterMessage(response)

AccountInfoWithTCStats = _reflection.GeneratedProtocolMessageType('AccountInfoWithTCStats', (_message.Message,), {
  'DESCRIPTOR' : _ACCOUNTINFOWITHTCSTATS,
  '__module__' : 'PlayerCSStats_pb2'
  # @@protoc_insertion_point(class_scope:PlayerCSStats.AccountInfoWithTCStats)
  })
_sym_db.RegisterMessage(AccountInfoWithTCStats)

DetailedTCStats = _reflection.GeneratedProtocolMessageType('DetailedTCStats', (_message.Message,), {
  'DESCRIPTOR' : _DETAILEDTCSTATS,
  '__module__' : 'PlayerCSStats_pb2'
  # @@protoc_insertion_point(class_scope:PlayerCSStats.DetailedTCStats)
  })
_sym_db.RegisterMessage(DetailedTCStats)


# @@protoc_insertion_point(module_scope)
