# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: PlayerStats.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='PlayerStats.proto',
  package='PlayerStats',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x11PlayerStats.proto\x12\x0bPlayerStats\"/\n\x07request\x12\x11\n\taccountid\x18\x01 \x01(\x04\x12\x11\n\tmatchmode\x18\x02 \x01(\r\"\xc3\x01\n\x08response\x12<\n\tsolostats\x18\x01 \x01(\x0b\x32).PlayerStats.AccountInfoWithStatsToClient\x12;\n\x08\x64uostats\x18\x02 \x01(\x0b\x32).PlayerStats.AccountInfoWithStatsToClient\x12<\n\tquadstats\x18\x03 \x01(\x0b\x32).PlayerStats.AccountInfoWithStatsToClient\"\x9c\x01\n\x1c\x41\x63\x63ountInfoWithStatsToClient\x12\x11\n\taccountid\x18\x01 \x01(\x04\x12\x13\n\x0bgamesplayed\x18\x02 \x01(\r\x12\x0c\n\x04wins\x18\x03 \x01(\r\x12\r\n\x05kills\x18\x04 \x01(\r\x12\x37\n\rdetailedstats\x18\x05 \x01(\x0b\x32 .PlayerStats.PlayerDetailedStats\"\x95\x02\n\x13PlayerDetailedStats\x12\x0e\n\x06\x64\x65\x61ths\x18\x01 \x01(\r\x12\x12\n\ntop10times\x18\x02 \x01(\r\x12\x11\n\ttopntimes\x18\x03 \x01(\r\x12\x19\n\x11\x64istancetravelled\x18\x04 \x01(\r\x12\x14\n\x0csurvivaltime\x18\x05 \x01(\r\x12\x0f\n\x07revives\x18\x06 \x01(\r\x12\x14\n\x0chighestkills\x18\x07 \x01(\r\x12\x0e\n\x06\x64\x61mage\x18\x08 \x01(\r\x12\x11\n\troadkills\x18\t \x01(\r\x12\x11\n\theadshots\x18\n \x01(\r\x12\x15\n\rheadshotkills\x18\x0b \x01(\r\x12\x11\n\tknockdown\x18\x0c \x01(\r\x12\x0f\n\x07pickups\x18\r \x01(\rb\x06proto3'
)




_REQUEST = _descriptor.Descriptor(
  name='request',
  full_name='PlayerStats.request',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='accountid', full_name='PlayerStats.request.accountid', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='matchmode', full_name='PlayerStats.request.matchmode', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=34,
  serialized_end=81,
)


_RESPONSE = _descriptor.Descriptor(
  name='response',
  full_name='PlayerStats.response',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='solostats', full_name='PlayerStats.response.solostats', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='duostats', full_name='PlayerStats.response.duostats', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='quadstats', full_name='PlayerStats.response.quadstats', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=84,
  serialized_end=279,
)


_ACCOUNTINFOWITHSTATSTOCLIENT = _descriptor.Descriptor(
  name='AccountInfoWithStatsToClient',
  full_name='PlayerStats.AccountInfoWithStatsToClient',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='accountid', full_name='PlayerStats.AccountInfoWithStatsToClient.accountid', index=0,
      number=1, type=4, cpp_type=4, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='gamesplayed', full_name='PlayerStats.AccountInfoWithStatsToClient.gamesplayed', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='wins', full_name='PlayerStats.AccountInfoWithStatsToClient.wins', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='kills', full_name='PlayerStats.AccountInfoWithStatsToClient.kills', index=3,
      number=4, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='detailedstats', full_name='PlayerStats.AccountInfoWithStatsToClient.detailedstats', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=282,
  serialized_end=438,
)


_PLAYERDETAILEDSTATS = _descriptor.Descriptor(
  name='PlayerDetailedStats',
  full_name='PlayerStats.PlayerDetailedStats',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='deaths', full_name='PlayerStats.PlayerDetailedStats.deaths', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='top10times', full_name='PlayerStats.PlayerDetailedStats.top10times', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='topntimes', full_name='PlayerStats.PlayerDetailedStats.topntimes', index=2,
      number=3, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='distancetravelled', full_name='PlayerStats.PlayerDetailedStats.distancetravelled', index=3,
      number=4, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='survivaltime', full_name='PlayerStats.PlayerDetailedStats.survivaltime', index=4,
      number=5, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='revives', full_name='PlayerStats.PlayerDetailedStats.revives', index=5,
      number=6, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='highestkills', full_name='PlayerStats.PlayerDetailedStats.highestkills', index=6,
      number=7, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='damage', full_name='PlayerStats.PlayerDetailedStats.damage', index=7,
      number=8, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='roadkills', full_name='PlayerStats.PlayerDetailedStats.roadkills', index=8,
      number=9, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='headshots', full_name='PlayerStats.PlayerDetailedStats.headshots', index=9,
      number=10, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='headshotkills', full_name='PlayerStats.PlayerDetailedStats.headshotkills', index=10,
      number=11, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='knockdown', full_name='PlayerStats.PlayerDetailedStats.knockdown', index=11,
      number=12, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='pickups', full_name='PlayerStats.PlayerDetailedStats.pickups', index=12,
      number=13, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=441,
  serialized_end=718,
)

_RESPONSE.fields_by_name['solostats'].message_type = _ACCOUNTINFOWITHSTATSTOCLIENT
_RESPONSE.fields_by_name['duostats'].message_type = _ACCOUNTINFOWITHSTATSTOCLIENT
_RESPONSE.fields_by_name['quadstats'].message_type = _ACCOUNTINFOWITHSTATSTOCLIENT
_ACCOUNTINFOWITHSTATSTOCLIENT.fields_by_name['detailedstats'].message_type = _PLAYERDETAILEDSTATS
DESCRIPTOR.message_types_by_name['request'] = _REQUEST
DESCRIPTOR.message_types_by_name['response'] = _RESPONSE
DESCRIPTOR.message_types_by_name['AccountInfoWithStatsToClient'] = _ACCOUNTINFOWITHSTATSTOCLIENT
DESCRIPTOR.message_types_by_name['PlayerDetailedStats'] = _PLAYERDETAILEDSTATS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

request = _reflection.GeneratedProtocolMessageType('request', (_message.Message,), {
  'DESCRIPTOR' : _REQUEST,
  '__module__' : 'PlayerStats_pb2'
  # @@protoc_insertion_point(class_scope:PlayerStats.request)
  })
_sym_db.RegisterMessage(request)

response = _reflection.GeneratedProtocolMessageType('response', (_message.Message,), {
  'DESCRIPTOR' : _RESPONSE,
  '__module__' : 'PlayerStats_pb2'
  # @@protoc_insertion_point(class_scope:PlayerStats.response)
  })
_sym_db.RegisterMessage(response)

AccountInfoWithStatsToClient = _reflection.GeneratedProtocolMessageType('AccountInfoWithStatsToClient', (_message.Message,), {
  'DESCRIPTOR' : _ACCOUNTINFOWITHSTATSTOCLIENT,
  '__module__' : 'PlayerStats_pb2'
  # @@protoc_insertion_point(class_scope:PlayerStats.AccountInfoWithStatsToClient)
  })
_sym_db.RegisterMessage(AccountInfoWithStatsToClient)

PlayerDetailedStats = _reflection.GeneratedProtocolMessageType('PlayerDetailedStats', (_message.Message,), {
  'DESCRIPTOR' : _PLAYERDETAILEDSTATS,
  '__module__' : 'PlayerStats_pb2'
  # @@protoc_insertion_point(class_scope:PlayerStats.PlayerDetailedStats)
  })
_sym_db.RegisterMessage(PlayerDetailedStats)


# @@protoc_insertion_point(module_scope)
