# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: SearchAccountByName.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from Proto.compiled import PlayerPersonalShow_pb2 as PlayerPersonalShow__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='SearchAccountByName.proto',
  package='SearchAccountByName',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x19SearchAccountByName.proto\x12\x13SearchAccountByName\x1a\x18PlayerPersonalShow.proto\"\x1a\n\x07request\x12\x0f\n\x07keyword\x18\x01 \x01(\t\"?\n\x08response\x12\x33\n\x05infos\x18\x01 \x03(\x0b\x32$.PlayerPersonalShow.AccountInfoBasicb\x06proto3'
  ,
  dependencies=[PlayerPersonalShow__pb2.DESCRIPTOR,])




_REQUEST = _descriptor.Descriptor(
  name='request',
  full_name='SearchAccountByName.request',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='keyword', full_name='SearchAccountByName.request.keyword', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=76,
  serialized_end=102,
)


_RESPONSE = _descriptor.Descriptor(
  name='response',
  full_name='SearchAccountByName.response',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='infos', full_name='SearchAccountByName.response.infos', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=104,
  serialized_end=167,
)

_RESPONSE.fields_by_name['infos'].message_type = PlayerPersonalShow__pb2._ACCOUNTINFOBASIC
DESCRIPTOR.message_types_by_name['request'] = _REQUEST
DESCRIPTOR.message_types_by_name['response'] = _RESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

request = _reflection.GeneratedProtocolMessageType('request', (_message.Message,), {
  'DESCRIPTOR' : _REQUEST,
  '__module__' : 'SearchAccountByName_pb2'
  # @@protoc_insertion_point(class_scope:SearchAccountByName.request)
  })
_sym_db.RegisterMessage(request)

response = _reflection.GeneratedProtocolMessageType('response', (_message.Message,), {
  'DESCRIPTOR' : _RESPONSE,
  '__module__' : 'SearchAccountByName_pb2'
  # @@protoc_insertion_point(class_scope:SearchAccountByName.response)
  })
_sym_db.RegisterMessage(response)


# @@protoc_insertion_point(module_scope)
